import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Hero from '@/components/Hero';
import DataLabeling from '@/components/DataLabeling';

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>My Digital Marketing Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Hero />
        <DataLabeling />
      </main>
    </div>
  );
};

export default Home;
