import Head from 'next/head';

import Hero from '@/components/Hero';
import Footer from '@/components/Footer';
import FAQs from '@/components/FAQs';
import Reviews from '@/components/Reviews';
import Navbar from '@/components/Navbar';
import DataLabeling from '@/components/DataLabeling';
import AnnouncementBanners from '@/components/ AnnouncementBanners';
import MockupWithText from '@/components/MockupWithText';
import WhyUs from '@/components/WhyUs';

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>My Digital Marketing Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <AnnouncementBanners /> */}
        <Navbar />
        <Hero />
        <MockupWithText />
        <WhyUs/>
        <Reviews />
        <FAQs />
        <Footer />
      </main>
    </div>
  );
};

export default Home;
